name: Comment on New Issues
on:
  issues:
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Issue
        if: github.event.issue.user.login != github.event.repository.owner.login
        uses: actions/github-script@0.10.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueComment = `
            🎉 Thanks for raising an issue for the ToDo-List project 🚀

            Our team will review your issue shortly. If everything checks out, we'll assign the issue to you 📋✅

            Your support is appreciated! 🌟 Please consider giving our repository a star ⭐ to show your support 🚀

            Feel free to ask any questions or provide additional context. We're here to help! 🙌
            `;

            github.issues.createComment({ issue_number: github.context.issue.number, owner: github.context.repo.owner, repo: github.context.repo.repo, body: issueComment });
